package com.hrdb;
// Generated 7 Oct, 2014 3:41:50 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


import javax.persistence.Transient;
import javax.persistence.CascadeType;


/**
 * User generated by hbm2java
 */
@Entity
@Table(name="USER"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
)
public class User  implements java.io.Serializable {


     private Integer userid;
     private String username;
     private String password;
     private String role;
     private Integer tenantid;

    public User() {
    }

    public User(String username, String password, String role, Integer tenantid) {
       this.username = username;
       this.password = password;
       this.role = role;
       this.tenantid = tenantid;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="USERID", unique=true, nullable=false)
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    
    @Column(name="USERNAME", length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="ROLE", length=20)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="TENANTID")
    public Integer getTenantid() {
        return this.tenantid;
    }
    
    public void setTenantid(Integer tenantid) {
        this.tenantid = tenantid;
    }




}

